version: "3.8"

services:
  mongo:
      image: mongodb/mongodb-community-server:7.0.23-ubi9
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db
      networks:
        - chat_app_network
      
volumes:
  mongodb_data: